[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]

[formatter.black]
command = "black"
options = ["--fast"]
includes = ["*.py", "*.pyi"]
